app:
  environment: prod

  clickhouse:
    host: "localhost"
    port: 8123
    database: "maxaira"
    username: "default"
    password: ""

  binance:
    assets: ["btc", "eth"]
    spot:
      ws_url: "wss://stream.binance.com:9443/ws/"
      rest_url: "https://api.binance.com/api/v3/klines"
    um:
      ws_url: "wss://fstream.binance.com/ws/"
      rest_url: "https://fapi.binance.com/fapi/v1/klines"
    cm:
      ws_url: "wss://dstream.binance.com/ws/"
      rest_url: "https://dapi.binance.com/dapi/v1/klines"
    historical_start_dates: "2020-01-01"
